### ISSUE TITLE
Database Error Handling

### ISSUE THREAD

**Issue by TortillaWrappedParrot** [NullPointer1331/GameShopManager#26]
If the database is failed to be fetched or the table, it tries to retrieve it returns an unhandled error.
![image](https://github.com/NullPointer1331/GameShopManager/assets/119008633/746b81bd-bbe4-4e41-bcac-9d78337f14d5)
![image](https://github.com/NullPointer1331/GameShopManager/assets/119008633/5b10dece-3002-459a-af94-37c9767c96bb)

**Comment by NullPointer1331** [comment]
did you run "database update" in the package manager console before trying to use the database?

**Comment by NullPointer1331** [comment]
oops, the command I meant to ask about was "Update-Database" not database update

**Comment by TortillaWrappedParrot** [comment]
Solved the issue but still would help those edge cases where either the connection doesn't work or a SQL command fails to execute.
